### ISSUE TITLE
The Dockerfile file is not working properly and inside container tomcat is not running

### ISSUE THREAD

**Issue by kannanchinnakannu94** [andrefernandes/docker-tomcat7#1]

**Comment by andrefernandes** [comment]
I am sorry, these are old projects from the time offical tomcat containers were not around. Any reason why you are not using the official tomcat images?

**Comment by andrefernandes** [comment]
I have rebuilt the base images and this image itself.

It now runs on IBM JDK (Oracle is, as usual, a real pain for people who want to be useful and recently made it harder to download their JDK in auto builds).

**Comment by kannanchinnakannu94** [comment]
thanks for your reply
